window.CAPRICHE_DATA = {
  "content": [
    {
      "ID": "C01",
      "Data": "2026-09-15",
      "Dia": "Terça",
      "Formato principal": "Reel",
      "Pilar": "Soluções por problema",
      "Tema": "Limpeza pós-obra",
      "Gancho / título": "A obra terminou. Mas ainda não está pronta para entregar.",
      "O que a Capriche precisa enviar ou gravar": "Vídeos verticais de um pós-obra: antes, equipe trabalhando e resultado final.",
      "Stories do dia": "Enquete: o que mais dá retrabalho na reta final da obra?",
      "Copy base": "A última etapa de uma obra também impacta a percepção de qualidade. A limpeza pós-obra remove resíduos, poeira fina e marcas que comprometem a entrega. A Capriche entra para deixar o ambiente realmente pronto.",
      "CTA": "Vai entregar uma obra? Solicite uma avaliação.",
      "Status Luciana": "A fazer",
      "Status Mais Ideias": "Planejado",
      "Horário": "13:30"
    },
    {
      "ID": "C02",
      "Data": "2026-09-16",
      "Dia": "Quarta",
      "Formato principal": "Stories",
      "Pilar": "Processo e segurança",
      "Tema": "Como a Capriche trabalha",
      "Gancho / título": "Antes de limpar, a gente avalia.",
      "O que a Capriche precisa enviar ou gravar": "Foto ou vídeo curto da equipe avaliando ambiente/equipamento.",
      "Stories do dia": "3 frames: avaliação → execução → inspeção.",
      "Copy base": "Cada superfície pede um procedimento diferente. Por isso o serviço começa com avaliação e termina com inspeção de qualidade.",
      "CTA": "Fale com a Capriche para avaliar seu ambiente.",
      "Status Luciana": "A fazer",
      "Status Mais Ideias": "Planejado",
      "Horário": "12:00"
    },
    {
      "ID": "C03",
      "Data": "2026-09-17",
      "Dia": "Quinta",
      "Formato principal": "Carrossel",
      "Pilar": "Autoridade técnica",
      "Tema": "Pós-obra",
      "Gancho / título": "5 erros que deixam o pós-obra com cara de obra.",
      "O que a Capriche precisa enviar ou gravar": "Fotos de resíduos, respingos, vidros/pisos e detalhes reais.",
      "Stories do dia": "Quiz: qual desses erros você mais encontra em obra?",
      "Copy base": "Poeira, respingos e resíduos podem comprometer até um ótimo acabamento. Pós-obra profissional não é só limpar: é preparar o ambiente para a entrega.",
      "CTA": "Salve este checklist e peça uma avaliação.",
      "Status Luciana": "A fazer",
      "Status Mais Ideias": "Planejado",
      "Horário": "12:30"
    },
    {
      "ID": "C04",
      "Data": "2026-09-18",
      "Dia": "Sexta",
      "Formato principal": "Imagem",
      "Pilar": "Soluções por segmento",
      "Tema": "Limpeza para empresas",
      "Gancho / título": "Empresa limpa também comunica organização.",
      "O que a Capriche precisa enviar ou gravar": "Foto de ambiente comercial, industrial ou corporativo atendido pela Capriche.",
      "Stories do dia": "Caixa: qual área da sua empresa mais exige manutenção?",
      "Copy base": "Para uma empresa, limpeza não é só aparência. Ela influencia experiência, percepção de cuidado e rotina operacional. A Capriche atende ambientes comerciais e corporativos com processo e equipe treinada.",
      "CTA": "Sua empresa precisa de uma solução sob medida? Fale conosco.",
      "Status Luciana": "A fazer",
      "Status Mais Ideias": "Planejado",
      "Horário": "11:30"
    },
    {
      "ID": "C05",
      "Data": "2026-09-19",
      "Dia": "Sábado",
      "Formato principal": "Stories",
      "Pilar": "Prova e resultados",
      "Tema": "Antes e depois",
      "Gancho / título": "Antes e depois que dispensa legenda.",
      "O que a Capriche precisa enviar ou gravar": "Um bom antes/durante/depois de qualquer serviço.",
      "Stories do dia": "3 frames: antes → durante → depois.",
      "Copy base": "Resultado bom aparece no detalhe. Use um caso real para mostrar transformação sem exagero publicitário.",
      "CTA": "Quer esse padrão no seu ambiente? Chame no WhatsApp.",
      "Status Luciana": "A fazer",
      "Status Mais Ideias": "Planejado",
      "Horário": "10:00"
    },
    {
      "ID": "C06",
      "Data": "2026-09-20",
      "Dia": "Domingo",
      "Formato principal": "Stories",
      "Pilar": "Prova e resultados",
      "Tema": "Depoimento",
      "Gancho / título": "Quem já trabalhou com a Capriche conta melhor.",
      "O que a Capriche precisa enviar ou gravar": "Depoimento curto autorizado de cliente/construtora + foto ou logo.",
      "Stories do dia": "Depoimento em 2 frames.",
      "Copy base": "Parceria boa é aquela que se repete. Mostrar a experiência de um cliente ajuda a reduzir o risco percebido por quem ainda não conhece a Capriche.",
      "CTA": "Conheça nossos serviços no site.",
      "Status Luciana": "A fazer",
      "Status Mais Ideias": "Planejado",
      "Horário": "17:00"
    },
    {
      "ID": "C07",
      "Data": "2026-09-21",
      "Dia": "Segunda",
      "Formato principal": "Carrossel",
      "Pilar": "Soluções por segmento",
      "Tema": "Checklist para construtoras",
      "Gancho / título": "Antes de contratar limpeza pós-obra, confira estes 6 pontos.",
      "O que a Capriche precisa enviar ou gravar": "Fotos da equipe, equipamentos e uma entrega real.",
      "Stories do dia": "Enquete: preço, prazo, equipe ou confiança — o que pesa mais?",
      "Copy base": "Em pós-obra, prazo, técnica e capacidade de execução pesam tanto quanto preço. Avalie processo, equipe, equipamentos e controle de qualidade.",
      "CTA": "Vai contratar para uma entrega? Fale com a Capriche.",
      "Status Luciana": "A fazer",
      "Status Mais Ideias": "Planejado",
      "Horário": "14:30"
    },
    {
      "ID": "C08",
      "Data": "2026-09-22",
      "Dia": "Terça",
      "Formato principal": "Reel",
      "Pilar": "Prova e resultados",
      "Tema": "Transformação",
      "Gancho / título": "Do resíduo ao brilho em poucos segundos.",
      "O que a Capriche precisa enviar ou gravar": "Vídeos verticais antes/depois com boa luz e enquadramento.",
      "Stories do dia": "Zoom em dois detalhes do resultado.",
      "Copy base": "Quando o serviço é bem executado, a diferença não precisa de explicação. Técnica, equipamento e atenção aos detalhes para entregar o ambiente pronto.",
      "CTA": "Peça uma avaliação para sua obra ou empresa.",
      "Status Luciana": "A fazer",
      "Status Mais Ideias": "Planejado",
      "Horário": "13:30"
    },
    {
      "ID": "C09",
      "Data": "2026-09-23",
      "Dia": "Quarta",
      "Formato principal": "Stories",
      "Pilar": "Marca e relacionamento",
      "Tema": "Perguntas e respostas",
      "Gancho / título": "Pergunte para a Capriche.",
      "O que a Capriche precisa enviar ou gravar": "Luciana disponível para responder 2 ou 3 dúvidas em vídeo.",
      "Stories do dia": "Caixa de perguntas sobre pós-obra, fachada, vidro, piso e empresas.",
      "Copy base": "Dúvidas reais geram conteúdo útil. Responder com exemplos simples ajuda a mostrar experiência sem parecer propaganda.",
      "CTA": "Envie sua pergunta.",
      "Status Luciana": "A fazer",
      "Status Mais Ideias": "Planejado",
      "Horário": "12:30"
    },
    {
      "ID": "C10",
      "Data": "2026-09-24",
      "Dia": "Quinta",
      "Formato principal": "Reel",
      "Pilar": "Processo e segurança",
      "Tema": "Fachadas / trabalho em altura",
      "Gancho / título": "Fachada em altura não combina com improviso.",
      "O que a Capriche precisa enviar ou gravar": "Vídeos de rapel, EPIs, preparação, execução e resultado.",
      "Stories do dia": "Mostrar um detalhe de segurança e explicar em uma frase.",
      "Copy base": "Trabalho em altura exige técnica, procedimento e profissionais preparados. A Capriche realiza limpeza externa e de fachadas com foco em segurança e acabamento.",
      "CTA": "Precisa avaliar fachada ou área externa? Fale conosco.",
      "Status Luciana": "A fazer",
      "Status Mais Ideias": "Planejado",
      "Horário": "12:30"
    },
    {
      "ID": "C11",
      "Data": "2026-09-25",
      "Dia": "Sexta",
      "Formato principal": "Imagem",
      "Pilar": "Prova e resultados",
      "Tema": "Clientes B2B",
      "Gancho / título": "Quem entrega empreendimento precisa de parceiro que cumpra o combinado.",
      "O que a Capriche precisa enviar ou gravar": "Logos autorizados de clientes ou 1 depoimento forte.",
      "Stories do dia": "Repost do depoimento ou logo de cliente.",
      "Copy base": "No B2B, confiança nasce de execução, prazo e consistência. Mostrar quem já contratou a Capriche reforça credibilidade.",
      "CTA": "Conheça nossos trabalhos e solicite uma avaliação.",
      "Status Luciana": "A fazer",
      "Status Mais Ideias": "Planejado",
      "Horário": "11:30"
    },
    {
      "ID": "C12",
      "Data": "2026-09-26",
      "Dia": "Sábado",
      "Formato principal": "Stories",
      "Pilar": "Processo e segurança",
      "Tema": "Equipamentos",
      "Gancho / título": "O equipamento certo economiza tempo e protege a superfície.",
      "O que a Capriche precisa enviar ou gravar": "Vídeo rápido de uma máquina/equipamento e sua função.",
      "Stories do dia": "1 equipamento + 1 frase explicando onde é usado.",
      "Copy base": "Limpeza profissional também é escolher a ferramenta certa para cada superfície.",
      "CTA": "Acompanhe os bastidores da Capriche.",
      "Status Luciana": "A fazer",
      "Status Mais Ideias": "Planejado",
      "Horário": "10:30"
    },
    {
      "ID": "C13",
      "Data": "2026-09-27",
      "Dia": "Domingo",
      "Formato principal": "Stories",
      "Pilar": "Autoridade técnica",
      "Tema": "Pisos",
      "Gancho / título": "Mito ou verdade: qualquer produto serve em qualquer piso?",
      "O que a Capriche precisa enviar ou gravar": "Foto de piso e, se possível, produto/equipamento utilizado.",
      "Stories do dia": "Quiz com resposta no frame seguinte.",
      "Copy base": "Cada material reage de um jeito. Produto inadequado pode manchar, retirar brilho ou reduzir a vida útil da superfície.",
      "CTA": "Tem dúvida sobre seu piso? Fale conosco.",
      "Status Luciana": "A fazer",
      "Status Mais Ideias": "Planejado",
      "Horário": "17:00"
    },
    {
      "ID": "C14",
      "Data": "2026-09-28",
      "Dia": "Segunda",
      "Formato principal": "Carrossel",
      "Pilar": "Autoridade técnica",
      "Tema": "ACM",
      "Gancho / título": "ACM opaco nem sempre precisa ser trocado.",
      "O que a Capriche precisa enviar ou gravar": "Fotos reais de ACM antes/depois.",
      "Stories do dia": "Enquete: seu ACM está sujo ou perdeu acabamento?",
      "Copy base": "Em muitos casos, limpeza técnica e restauração ajudam a devolver aparência e brilho ao ACM sem partir direto para substituição.",
      "CTA": "Quer avaliar o ACM da sua empresa? Fale com a Capriche.",
      "Status Luciana": "A fazer",
      "Status Mais Ideias": "Planejado",
      "Horário": "14:30"
    },
    {
      "ID": "C15",
      "Data": "2026-09-29",
      "Dia": "Terça",
      "Formato principal": "Reel",
      "Pilar": "Soluções por problema",
      "Tema": "Vidros riscados",
      "Gancho / título": "Risco no vidro nem sempre significa troca.",
      "O que a Capriche precisa enviar ou gravar": "Vídeo macro do risco, processo e resultado; somente casos tecnicamente adequados.",
      "Stories do dia": "Quiz: trocar ou recuperar?",
      "Copy base": "Antes de trocar um vidro riscado, vale avaliar se o dano permite recuperação. A Capriche realiza remoção técnica em situações adequadas, sempre após análise.",
      "CTA": "Tem vidro riscado? Solicite avaliação.",
      "Status Luciana": "A fazer",
      "Status Mais Ideias": "Planejado",
      "Horário": "13:30"
    },
    {
      "ID": "C16",
      "Data": "2026-09-30",
      "Dia": "Quarta",
      "Formato principal": "Carrossel",
      "Pilar": "Autoridade técnica",
      "Tema": "Pisos / impermeabilização",
      "Gancho / título": "Piso bonito por mais tempo começa na proteção certa.",
      "O que a Capriche precisa enviar ou gravar": "Fotos de pisos tratados e detalhes de acabamento.",
      "Stories do dia": "Enquete: o que mais desgasta o piso da sua empresa?",
      "Copy base": "Em áreas de alto tráfego, o piso sofre todos os dias. Tratamento e impermeabilização ajudam na conservação e facilitam a manutenção.",
      "CTA": "Quer avaliar o piso da sua empresa? Solicite orçamento.",
      "Status Luciana": "A fazer",
      "Status Mais Ideias": "Planejado",
      "Horário": "12:30"
    },
    {
      "ID": "C17",
      "Data": "2026-10-01",
      "Dia": "Quinta",
      "Formato principal": "Reel",
      "Pilar": "Soluções por segmento",
      "Tema": "Comercial / industrial",
      "Gancho / título": "Grandes operações não podem depender de improviso.",
      "O que a Capriche precisa enviar ou gravar": "Equipe chegando, equipamentos, execução em ambiente amplo e inspeção final.",
      "Stories do dia": "Enquete: limpeza pontual ou recorrente?",
      "Copy base": "Quando o ambiente é grande, o desafio não é só limpar. É planejar e executar sem atrapalhar a operação. A Capriche trabalha com atendimento sob medida para empresas.",
      "CTA": "Precisa estruturar uma demanda comercial ou industrial? Fale conosco.",
      "Status Luciana": "A fazer",
      "Status Mais Ideias": "Planejado",
      "Horário": "12:30"
    },
    {
      "ID": "C18",
      "Data": "2026-10-02",
      "Dia": "Sexta",
      "Formato principal": "Imagem",
      "Pilar": "Processo e segurança",
      "Tema": "Método de trabalho",
      "Gancho / título": "Avaliar. Executar. Inspecionar.",
      "O que a Capriche precisa enviar ou gravar": "Foto da equipe + se possível checklist ou imagem de inspeção.",
      "Stories do dia": "Bastidor da inspeção final.",
      "Copy base": "Bom serviço não depende de sorte. A Capriche trabalha com avaliação inicial, procedimento adequado e inspeção de qualidade ao final.",
      "CTA": "Quer um orçamento bem dimensionado? Solicite uma avaliação.",
      "Status Luciana": "A fazer",
      "Status Mais Ideias": "Planejado",
      "Horário": "11:30"
    },
    {
      "ID": "C19",
      "Data": "2026-10-03",
      "Dia": "Sábado",
      "Formato principal": "Stories",
      "Pilar": "Prova e resultados",
      "Tema": "Melhor case do ciclo",
      "Gancho / título": "Um bom antes e depois vale por mil promessas.",
      "O que a Capriche precisa enviar ou gravar": "Escolher o melhor case produzido nas duas semanas anteriores.",
      "Stories do dia": "Repost do melhor resultado.",
      "Copy base": "Reforce visualmente o padrão de execução da Capriche com um caso real.",
      "CTA": "Precisa de orçamento? Chame no WhatsApp.",
      "Status Luciana": "A fazer",
      "Status Mais Ideias": "Planejado",
      "Horário": "10:30"
    },
    {
      "ID": "C20",
      "Data": "2026-10-04",
      "Dia": "Domingo",
      "Formato principal": "Stories",
      "Pilar": "Marca e relacionamento",
      "Tema": "Pesquisa de interesse",
      "Gancho / título": "Qual serviço você quer ver em detalhe esta semana?",
      "O que a Capriche precisa enviar ou gravar": "Nenhum material novo; usar imagens já disponíveis.",
      "Stories do dia": "Enquete: pós-obra / fachada / vidro / piso.",
      "Copy base": "A próxima pauta pode nascer da dúvida do público. O objetivo é entender quais serviços despertam mais interesse.",
      "CTA": "Vote e, se tiver uma demanda, fale com a Capriche.",
      "Status Luciana": "A fazer",
      "Status Mais Ideias": "Planejado",
      "Horário": "17:00"
    }
  ],
  "materials": [
    {
      "ID": "M01",
      "Material": "Vídeos antes/durante/depois de limpeza pós-obra",
      "Para que será usado": "Reels, carrosséis e primeiro anúncio Meta Ads",
      "Prioridade": "Alta",
      "Status": "Pendente",
      "Observação da Luciana": null,
      "Observação Mais Ideias": "Preferir vídeos verticais e boa luz."
    },
    {
      "ID": "M02",
      "Material": "Vídeos de trabalho em altura / rapel + EPIs",
      "Para que será usado": "Conteúdo de segurança + anúncio de fachada",
      "Prioridade": "Alta",
      "Status": "Pendente",
      "Observação da Luciana": null,
      "Observação Mais Ideias": "Mostrar preparação, execução e resultado."
    },
    {
      "ID": "M03",
      "Material": "Fotos/vídeos de ambientes comerciais ou industriais",
      "Para que será usado": "Campanha B2B e conteúdo para empresas",
      "Prioridade": "Alta",
      "Status": "Pendente",
      "Observação da Luciana": null,
      "Observação Mais Ideias": "Buscar ambientes maiores e visualmente organizados."
    },
    {
      "ID": "M04",
      "Material": "Fotos de ACM antes/depois",
      "Para que será usado": "Carrossel técnico e prova de serviço",
      "Prioridade": "Média",
      "Status": "Pendente",
      "Observação da Luciana": null,
      "Observação Mais Ideias": "Usar somente casos com autorização."
    },
    {
      "ID": "M05",
      "Material": "Fotos/vídeos de vidros com risco e recuperação",
      "Para que será usado": "Reel técnico e conteúdo educativo",
      "Prioridade": "Média",
      "Status": "Pendente",
      "Observação da Luciana": null,
      "Observação Mais Ideias": "Evitar promessas de recuperação sem avaliação."
    },
    {
      "ID": "M06",
      "Material": "Fotos de pisos tratados / impermeabilizados",
      "Para que será usado": "Carrossel e Stories educativos",
      "Prioridade": "Média",
      "Status": "Pendente",
      "Observação da Luciana": null,
      "Observação Mais Ideias": "Detalhes de brilho/acabamento ajudam."
    },
    {
      "ID": "M07",
      "Material": "Fotos da equipe e equipamentos",
      "Para que será usado": "Bastidores, processo e autoridade",
      "Prioridade": "Alta",
      "Status": "Pendente",
      "Observação da Luciana": null,
      "Observação Mais Ideias": "Fotos naturais, equipe em ação."
    },
    {
      "ID": "M08",
      "Material": "Logos de clientes/construtoras autorizados",
      "Para que será usado": "Prova social no Feed e anúncios",
      "Prioridade": "Alta",
      "Status": "Pendente",
      "Observação da Luciana": null,
      "Observação Mais Ideias": "Confirmar autorização de uso."
    },
    {
      "ID": "M09",
      "Material": "Depoimentos de clientes B2B",
      "Para que será usado": "Prova social e Stories",
      "Prioridade": "Alta",
      "Status": "Pendente",
      "Observação da Luciana": null,
      "Observação Mais Ideias": "Texto curto com nome/empresa quando autorizado."
    },
    {
      "ID": "M10",
      "Material": "Dúvidas frequentes que clientes fazem",
      "Para que será usado": "Stories, Reels e conteúdo educativo",
      "Prioridade": "Média",
      "Status": "Pendente",
      "Observação da Luciana": null,
      "Observação Mais Ideias": "Pode enviar por áudio ou texto."
    },
    {
      "ID": "M11",
      "Material": "Datas de obras/serviços programados nas próximas semanas",
      "Para que será usado": "Planejamento de captação de conteúdo",
      "Prioridade": "Alta",
      "Status": "Pendente",
      "Observação da Luciana": null,
      "Observação Mais Ideias": "Permite organizar gravação antes do serviço."
    },
    {
      "ID": "M12",
      "Material": "Confirmar WhatsApp comercial que receberá os leads",
      "Para que será usado": "Campanha Meta Ads",
      "Prioridade": "Alta",
      "Status": "Pendente",
      "Observação da Luciana": null,
      "Observação Mais Ideias": "Garantir atendimento rápido aos contatos."
    }
  ],
  "ideas": [
    {
      "id": "I01",
      "title": "Quanto tempo leva uma limpeza pós-obra?",
      "pillar": "Autoridade técnica",
      "status": "Ideia"
    },
    {
      "id": "I02",
      "title": "O que uma construtora deve avaliar antes de contratar a limpeza final?",
      "pillar": "Soluções por segmento",
      "status": "Próximo mês"
    },
    {
      "id": "I03",
      "title": "Limpeza técnica x limpeza convencional: qual a diferença?",
      "pillar": "Autoridade técnica",
      "status": "Ideia"
    },
    {
      "id": "I04",
      "title": "Como a Capriche organiza um serviço em ambiente com operação ativa?",
      "pillar": "Processo e segurança",
      "status": "Ideia"
    },
    {
      "id": "I05",
      "title": "Antes e depois: recuperação visual de ACM",
      "pillar": "Prova e resultados",
      "status": "Aprovada"
    },
    {
      "id": "I06",
      "title": "3 erros que podem danificar pisos de alto tráfego",
      "pillar": "Autoridade técnica",
      "status": "Próximo mês"
    }
  ],
  "campaigns": {
    "period": "15/09/2026 a 15/10/2026",
    "platform": "Meta Ads — Instagram + Facebook",
    "mediaBudget": 950,
    "management": 1000,
    "total": 1950,
    "objective": "Gerar contatos e conversas qualificadas",
    "destination": "WhatsApp, com apoio do site",
    "region": "Joinville em prioridade + região próxima de forma controlada",
    "stages": [
      {
        "name": "Teste",
        "period": "15–21/09",
        "budget": 220,
        "action": "Colocar 3 ângulos no ar sem fragmentar demais o orçamento.",
        "goal": "Descobrir qual mensagem gera mais atenção e conversas."
      },
      {
        "name": "Otimização",
        "period": "22/09–05/10",
        "budget": 440,
        "action": "Reduzir verba dos anúncios fracos e manter os melhores.",
        "goal": "Identificar serviços e criativos com contatos de melhor qualidade."
      },
      {
        "name": "Concentração",
        "period": "06–15/10",
        "budget": 290,
        "action": "Concentrar investimento no que comprovou melhor resposta.",
        "goal": "Criar uma base clara para o segundo mês."
      }
    ],
    "angles": [
      {
        "name": "Pós-obra",
        "format": "Reel 15–25s",
        "hook": "A obra terminou. Mas ainda não está pronta para entregar.",
        "audience": "Construtoras, incorporadoras, engenheiros e responsáveis por entrega de obra.",
        "cta": "Solicitar avaliação pelo WhatsApp",
        "material": "Antes/durante/depois de pós-obra."
      },
      {
        "name": "Fachadas / trabalho em altura",
        "format": "Reel 15–25s",
        "hook": "Fachada em altura não combina com improviso.",
        "audience": "Empresas, condomínios e gestores de manutenção/facilities.",
        "cta": "Solicitar avaliação",
        "material": "Vídeos de rapel, EPIs, execução e resultado."
      },
      {
        "name": "Empresas / indústrias",
        "format": "Reel ou imagem",
        "hook": "Grandes operações não podem depender de improviso.",
        "audience": "Indústrias, grandes lojas, redes e empresas com ambientes amplos.",
        "cta": "Falar com a Capriche",
        "material": "Equipe, máquinas, ambiente grande e inspeção."
      }
    ]
  }
};
